pure prompt: do not fetch in the background
It causes weird git errors like this:

  error: short read: Success
  error: foo.py: failed to insert into database
  fatal: cannot hash foo.py

and is a bit wasteful